from centos:7
MAINTAINER mike "mike@365oa.com"  

#保存自己的构建脚本
WORKDIR /
copy dockerfile dockerfile
copy readme.txt readme.txt

# set timezome  
ENV TZ=Asia/Shanghai  
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone 
 
#initscripts service  
RUN yum  -y update \ 
    yum install -y wget gcc  gcc-c++ make cmake perl autoconf automake zlib  libgcrypt curl libtool bison \
	ncurses-devel \  
	openssl-devel \  
	diffutils \ 
	initscripts \ 
	libtirpc-devel

#Redis-4.0.14
RUN	mkdir /download 
WORKDIR /download 

RUN  wget https://github.com/thkukuk/rpcsvc-proto/releases/download/v1.4/rpcsvc-proto-1.4.tar.gz \
&&  tar zxvf rpcsvc-proto-1.4.tar.gz 

WORKDIR /download/rpcsvc-proto-1.4
RUN ./configure && make && make install
 
WORKDIR /download 

#COPY mysql-boost-5.7.28.tar.gz /download/ 
# 壹共享生产环境是5.7.35  生产环境必须为GA release  版本5.7.28即为GA release 所以使用了5.7.28 
# mysql-boost-5.7.28 性能为 mysql 5.7 2倍 故采用8.0 GA release
# https://cdn.mysql.com//Downloads/MySQL-8.0/mysql-boost-5.7.28.tar.gz
RUN wget https://cdn.mysql.com//Downloads/MySQL-5.7/mysql-boost-5.7.28.tar.gz
RUN tar zxvf mysql-boost-5.7.28.tar.gz 

WORKDIR /download/mysql-5.7.28
 
#boost库，带boost的源码包只需要这样即可,不带boost源码包需要指明boost目录 
RUN  cmake . \
-DMYSQL_USER=mysql  \
-DCMAKE_INSTALL_PREFIX=/usr/local/mysql \
-DWITH_INNOBASE_STORAGE_ENGINE=1  \
-DWITH_MYISAM_STORAGE_ENGINE=1  \
-DWITH_MEMORY_STORAGE_ENGINE=1  \
-DWITH_EXTRA_CHARSETS=all \
-DDEFAULT_CHARSET=utf8  \
-DDEFAULT_COLLATION=utf8_general_ci \
-DWITH_EXTRA_CHARSETS=all  \
-DMYSQL_UNIX_ADDR=/tmp/mysql.sock \
-DMYSQL_DATADIR=/usr/local/mysql/data \
-DFORCE_INSOURCE_BUILD=1 \
-DWITH_BOOST=boost \  
&& make \
&& make install 

RUN cp packaging/rpm-docker/my.cnf  /etc/my.cnf \
    && mkdir /usr/local/mysql/log \
	&& touch /usr/local/mysql/log/error.log
	
RUN groupadd mysql  
RUN useradd mysql -M -g mysql -s /sbin/nologin 
RUN chown mysql:mysql /etc/my.cnf  
RUN chown -R mysql:mysql /usr/local/mysql
RUN echo "export PATH=/usr/local/mysql/bin:$PATH" >> /etc/profile  
RUN source /etc/profile

## 使用cat 替换 /etc/my.cnf配置
CMD  cat > /etc/my.cnf <<EOF  \
[client]  \
socket=/tmp/mysql.sock  \

[mysqld]  \
symbolic-links=0   \
server_id                  = 120   \
default_storage_engine    = Innodb  \
user                      = mysql  \
basedir                    = /usr/local/mysql  \
datadir                    = /usr/local/mysql/data  \
tmpdir                    = /home/mysql/tmp \
socket                    = /tmp/mysql.sock  \
pid_file                  = /tmp/mysql.pid  \
character_set_server      = utf8  \
collation_server          = utf8_general_ci  \
open_files_limit          = 10240  \
explicit_defaults_for_timestamp  \
max_allowed_packet        = 256M  \
max_heap_table_size        = 256M  \
net_buffer_length          = 8K  \
sort_buffer_size          = 2M  \
join_buffer_size          = 4M \
read_buffer_size          = 2M \
read_rnd_buffer_size      = 16M \
log_error                  = /usr/local/mysql/log/error.log \
log_bin                    = /usr/local/mysql/binlog/mysql-bin \
binlog_cache_size          = 32M \
max_binlog_cache_size      = 2G \
max_binlog_size            = 500M \
binlog_format              = mixed \
log_output                = FILE \
expire_logs_days          = 5 \
slow_query_log            = 1 \
long_query_time            = 3 \
slow_query_log_file        = /usr/local/mysql/log/slow-query.log \
innodb_buffer_pool_size    = 500M \
innodb_log_file_size      = 200M \
innodb_log_files_in_group  = 3 \
innodb_lock_wait_timeout  = 20 \

[mysql] \
no_auto_rehash \

[mysqld_safe] \
log-error=/usr/local/mysql/log/error.log \
EOF

RUN mysqld --initialize-insecure --user=mysql --basedir=/usr/local/mysql --datadir=/usr/local/mysql/data  --defaults-file=/etc/my.cnf  
#./scripts/mysql_install_db --defaults-file=/etc/my.cnf --user=mysql

#启动mysql
CMD mysqld_safe --user=mysql &

RUN cp /usr/local/mysql/support-files/mysql.server /etc/init.d/mysqld

RUN rm -Rf /download/*	 

#添加到启动列表
RUN chkconfig --add mysqld    
# 添加到启动列表        
RUN chkconfig mysqld on   
RUN service mysqld restart

 
